version: '3.4'

# 本文件 仅用作 Debug 用

services:
  simcaptcha.service:
    build:
      context: .
      dockerfile: examples/EasyAspNetCoreService/Dockerfile.Debug
    # 当同时设置 build, image 时，image 名将作为最后的镜像名
    image: simcaptcha-debug
    container_name: simcaptcha-debug-container
    ports:
      - "5004:80"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Docker
      # 注意：http://*:80 不要用 双引号 "" 引起来
      - ASPNETCORE_URLS=http://*:80
    networks:
      - simcaptcha-net

  simcaptcha.client:
    build:
      context: .
      dockerfile: examples/AspNetCoreClient/Dockerfile.Debug
    image: simcaptcha-client-debug
    container_name: simcaptcha-client-debug-container
    ports:
      - "5002:80"
    restart: always
    depends_on:
      - simcaptcha.service
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:80
    networks:
      - simcaptcha-net

networks:
  simcaptcha-net:
    driver: bridge