version: '3.4'

# 本文件 用作 Release 用，用作 Docker 部署

services:
  simcaptcha.service:
    image: yiyungent/simcaptcha
    container_name: simcaptcha-container
    ports:
      - "5004:80"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Docker
      # 注意：http://*:80 不要用 双引号 "" 引起来
      - ASPNETCORE_URLS=http://*:80
    networks:
      - simcaptcha-net

  simcaptcha.client:
    image: yiyungent/simcaptcha-client
    container_name: simcaptcha-client-container
    ports:
      - "5002:80"
    restart: always
    depends_on:
      - simcaptcha.service
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:80
    networks:
      - simcaptcha-net

networks:
  simcaptcha-net:
    driver: bridge